### ISSUE TITLE
Add state id based on Indonesia GeoJSON data

### ISSUE THREAD

**Issue by dion-ricky** [dion-ricky/future-data-1#10]
| Relationship | Priority | Est. Time |
| :--: | :--: | :--: |
| Parallel with #2 | `Medium` | 2 days |
---

Add state_id to match with `state` column for Metabase map visualization. Indonesia GeoJSON data can be found [here](https://storage.googleapis.com/dionricky-static/indonesia-updated.geojson).

**Example:**
| seller_state | seller_state_id |
| :--: | :--: |
| DKI JAKARTA | 8 |
| SUMATERA BARAT | 31 |
| JAWA TIMUR | 12 |

**Todo:**
- [x] Extract GeoJSON properties to csv
- [x] Add feature for new province 😭 `Kalimantan Utara`
- [x] Change UPPER CASE to Capitalized Case
- [x] Change `DKI JAKARTA` to `Jakarta Raya`
- [x] Change `DI Yogyakarta` to `Yogyakarta`
- [x] Change `KEPULAUAN BANGKA BELITUNG` to `Bangka-Belitung`
- [x] Change `PAPUA BARAT` to `Irian Jaya Barat`
- [x] Seller dimension
- [x] User/cust. dimension
