### ISSUE TITLE
[#20] Migrate + ETL warehouse.location_dim

### ISSUE THREAD

**Issue by dion-ricky** [dion-ricky/future-data-1#22]
| Relationship | Priority | Est. Time |
| :--: | :--: | :--: |
| Parallel with #20 | `High\Medium\Low` | 1 day |
---

Migrate dimension table location to warehouse from:
- ext_provinsi_pulau
- ext_lat_long_kabko
- ext_pdrb
- ext_state_population

**Todo:**
- [x] ext_provinsi_pulau
- [x] ext_lat_long_kabko
- [x] ext_pdrb
- [x] #23
- [x] temp_indonesia_geoprops
