### ISSUE TITLE
Configure DWH/DMT

### ISSUE THREAD

**Issue by dion-ricky** [dion-ricky/future-data-1#6]
**After #5**

Setelah database terbentuk maka perlu melakukan analisis untuk mencari subjek untuk menyusun DWH.

**Todo:**
- [x] Buat database baru khusus utk DWH
- [x] Cari business requirement
- [x] Buat information package
- [x] Buat schema baru utk setiap subject

**Comment by dion-ricky** [comment]
Update **17 Feb 2021**

## Shipping Analysis
_**Information Subject:** Shipping Analysis_
Memungkinkan analisa mengenai pengiriman, mulai dari biaya pengiriman, kecepatan pengiriman (`pickup_date` - `delivered_date`), ketepatan dengan `estimated_time_delivery`, rerata lama pickup sejak order (`order_approved_date`  - `pickup_date`), rasio `shipping_cost` terhadap `price`.

**Dimensions**
| Time | Seller | Customer |
| :----: | :-----: | :----------: |
| Tahun   | Provinsi | Provinsi |
| Kuartal | Kota      | Kota       |
| Bulan   |              |                |

_**Measured Facts:**_ rerata biaya pengiriman, total biaya pengiriman, jumlah total pengiriman, rerata kecepatan pengiriman, rerata selisih `delivered_date` dengan `estimated_time_delivery`, rerata lama pickup sejak order disetujui, rerata rasio `shipping_cost` terhadap harga barang yang dibeli

## Payment Analysis
_**Information Subject:** Payment Analysis_
Menemukan informasi mengenai metode pembayaran yang digunakan oleh customer

**Dimensions**
| Time | Customer | Payment |
| :--: | :--: | :--: |
| Tahun | Provinsi | Jenis Pembayaran |
| Kuartal |  Kota  |         |
| Bulan   |            |         |

_**Measured Facts:**_ rerata nilai pembayaran, total nilai pembayaran, rerata cicilan, banyaknya pembayaran

## Product Analysis
_**Information Subject:** Product Analysis_
Memperoleh informasi mengenai produk yang dibeli oleh customer

**Dimensions**
| Time | Product |
| :--: | :--: |
| Tahun | Kategori |
| Kuartal |  |
| Bulan |  |

_**Measured Facts:**_ rerata harga, rerata biaya pengiriman, total penjualan

**Comment by dion-ricky** [comment]
## Feedback Analysis
_**Information Subject:** Feedback Analysis_
Mengetahui informasi mengenai feedback dari customer

**Dimensions**
| Time | Product | Seller | Order |
| :----: | :--------: | :-----: | :-----: |
| Tahun | Kategori | Provinsi | Status |
| Kuartal | | Kota | |
| Bulan | | | |

_**Measured Facts:**_ rerata skor feedback, rerata selisih `feedback_answer_date` dengan `feedback_form_sent_date`

**Comment by dion-ricky** [comment]
Update **20 Feb 2021**

## Shipping Analysis
_**Information Subject:** Shipping Analysis_
Memungkinkan analisa mengenai pengiriman

**Fact table type:** Transaction fact

**Dimensions:** Time (order date), Seller, Customer

_**Measured Facts:**_ biaya pengiriman, kecepatan pengiriman, estimated delivery accuracy, pickup time, shipping cost vs product price ratio

**Comment by dion-ricky** [comment]
## Payment Analysis
_**Information Subject:** Payment Analysis_
Menemukan informasi mengenai metode pembayaran yang digunakan oleh customer

**Fact table type:** Transaction fact

**Dimensions:** Time (order date), Customer, Payment, Order item

_**Measured Facts:**_ nilai pembayaran, jumlah cicilan

**Comment by dion-ricky** [comment]
## Seller Order Analysis
_**Information Subject:** Seller Order Analysis_

**Fact table type:** Transaction fact

**Dimensions:** Time (order date), Seller, Order Item

**_Measured Facts:_** product price, shipping cost, shipping time

**Comment by dion-ricky** [comment]
## Product Analysis
_**Information Subject:** Product Analysis_
Memperoleh informasi mengenai produk yang dibeli oleh customer

**Dimensions**
| Time | Product |
| :--: | :--: |
| Tahun | Kategori |
| Kuartal | Product ID |
| Bulan |  |

_**Measured Facts:**_ rerata harga, rerata biaya pengiriman, total penjualan
