### ISSUE TITLE
Tableau Dashboard for Reporting

### ISSUE THREAD

**Issue by dion-ricky** [dion-ricky/future-data-1#7]
| Relationship | Priority | Est. Time |
| :--: | :--: | :--: |
| Parallel with #8 | `Medium` | 5 days |
---

Membuat dashboard reporting di Tableau

**Todo:**
- [ ] Referring to https://github.com/dion-ricky/future-data/issues/2#issuecomment-799435720
  - [ ] Kumulatif penjualan produk
  - [x] Penjualan produk per kategori
  - [x] Penjualan produk per wilayah customer
  - [ ] Pembayaran per tipe
  - [ ] Avg amount utk voucher

**Comment by dion-ricky** [comment]
Closed, change of plan
